# Generated by Django 5.2.14 on 2026-06-06 12:21

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaketTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, unique=True, verbose_name='Макет turi nomi')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL manzil)')),
                ('rasm', models.ImageField(upload_to=common.models.maket_tur_rasm_manzili, verbose_name='Maket turi rasmi')),
                ('malumot', models.TextField(blank=True, null=True, verbose_name="Kichik tavsif / Ma'lumot")),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name="Ko'rinish tartibi")),
            ],
            options={
                'verbose_name': 'Maket turi',
                'verbose_name_plural': 'Maket turlari',
                'ordering': ['tartib', 'id'],
            },
        ),
    ]
