# Generated by Django 5.2.14 on 2026-06-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='sliders/mobile/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Mobil Slayder',
                'verbose_name_plural': 'Mobil Slayderlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Quyi sarlavha')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='Rasm')),
                ('page', models.CharField(choices=[('home', 'Bosh sahifa'), ('projects', 'Projects'), ('project_types', 'Tip Maketov'), ('about', 'About'), ('contact', 'Contact'), ('blog', 'Blog'), ('services', 'Services'), ('mobile', 'Mobil versiya uchun')], default='home', max_length=50, verbose_name='Qaysi sahifada chiqsin')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('button_text', models.CharField(blank=True, default='Batafsil', max_length=100, verbose_name='Tugma matni')),
                ('button_url', models.CharField(blank=True, max_length=200, verbose_name='Tugma linki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Slayderlar',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Tel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='companies/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
