# Generated by Django 5.2.14 on 2026-06-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_mobileslider_slider_tel_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='page',
            field=models.CharField(choices=[('home', 'Bosh sahifa'), ('projects', 'Projects'), ('project-details', 'Project Details'), ('project_types', 'Tip Maketov'), ('about', 'About'), ('team', 'Team'), ('contact', 'Contact'), ('blog', 'Blog'), ('blog-details', 'Blog Details'), ('services', 'Services'), ('services-details', 'Services Details'), ('mobile', 'Mobil versiya uchun')], default='home', max_length=50, verbose_name='Qaysi sahifada chiqsin'),
        ),
    ]
