# Generated by Django 5.2.14 on 2026-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_slider_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('subtitle', models.TextField(blank=True, verbose_name='Quyi matn')),
                ('background_image', models.ImageField(upload_to='hero/', verbose_name='Background rasmi')),
                ('secondary_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Ikkinchi rasm')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['order'],
            },
        ),
    ]
