# Generated by Django 5.2.14 on 2026-06-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_herosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.FileField(upload_to='hero/', verbose_name='Background rasmi'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondary_image',
            field=models.FileField(blank=True, null=True, upload_to='hero/', verbose_name='Ikkinchi rasm'),
        ),
    ]
