# Generated by Django 5.2.14 on 2026-06-06 12:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='services/')),
                ('short_description', models.TextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
