# Generated by Django 5.2.14 on 2026-06-06 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kompaniya nomi')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='Logotip')),
                ('website', models.URLField(blank=True, verbose_name="Veb-sayti (agar bo'lsa)")),
            ],
            options={
                'verbose_name': 'Mijoz/Hamkor',
                'verbose_name_plural': 'Mijoz va Hamkorlar',
            },
        ),
        migrations.CreateModel(
            name='MockupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Maket turi nomi')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Maket turi',
                'verbose_name_plural': 'Maket turlari',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Loyiha nomi')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Loyiha haqida batafsil')),
                ('main_image', models.ImageField(upload_to='projects/', verbose_name='Asosiy rasm')),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='Buyurtmachi/Mijoz nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('mockup_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.mockuptype', verbose_name='Maket turi')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
